### ISSUE TITLE
ErrorCode format is not appropriate

### ISSUE THREAD

**Issue by ZhouShengsheng** [Dream27/be-dream-world#1]
![image](https://user-images.githubusercontent.com/8213501/35500794-9de1ce60-0512-11e8-9e8e-34241c94bcf4.png)

You can actually use every decimal digit to represent a different kind of error. But as a result, **every kind of error can only contains a maximum number of 10 errors, which is not sufficient.**

I suggest **using a four-digit number to represent an error code. Where the first two digits stands for error category and the last two digits tells specific error.** For example:

```java
public static final Integer ErrorCode_1000 = 1001; // username/email or password error 
public static final Integer ErrorCode_1001 = 1001; // user has logged in
public static final Integer ErrorCode_1100 = 1100; // travel note not found
public static final Integer ErrorCode_1101 = 1101; // add travel note error
```

**Comment by Dream27** [comment]
@ZhouShengsheng fixed: https://github.com/Dream27/be-dream-world/commit/cebfa746eed83bf45566a2cb7e3fe5a444d0b647
