### ISSUE TITLE
DFS functions should be moved to a standalone class

### ISSUE THREAD

**Issue by ZhouShengsheng** [Dream27/be-dream-world#2]
![image](https://user-images.githubusercontent.com/8213501/35501364-a0832360-0514-11e8-9b00-a2ed58757f8e.png)

DFS is not only used to upload and download image. It can manipulate any kind of file. You should write another util class named `DFSUtil` or `FileUtil` and move file-related operations into the class.

**Comment by Dream27** [comment]
@ZhouShengsheng fixed: https://github.com/Dream27/be-dream-world/commit/3ec924da91cb967e06bfae5ea9a57b795fe6e994
