### ISSUE TITLE
Active url in the active email is hardcoded with localhost

### ISSUE THREAD

**Issue by ZhouShengsheng** [Dream27/be-dream-world#3]
![image](https://user-images.githubusercontent.com/8213501/35503858-4fb195c2-051c-11e8-9f13-51eb3456ba3f.png)

Abstract the **url** into `application.yml`.

**Comment by Dream27** [comment]
@ZhouShengsheng fixed: https://github.com/Dream27/be-dream-world/commit/3ec924da91cb967e06bfae5ea9a57b795fe6e994
